#!/bin/sh

# Экспортируем все существующие пути где могут лежать приложения
export PATH="/usr/bin:/usr/local/bin:/opt/local/bin:$PATH"

# CMake адрес
readonly CMAKE_PATH=$(cmake --system-information | grep CMAKE_ROOT | cut -d= -f2 | awk '{print $2}' | sed "s/^\([\"']\)\(.*\)\1\$/\2/g")
# Адрес размещения файла CMake
readonly CMAKE_PATH_AWH="/usr/share/awh/cmake"

# Если адрес файла CMake существует
if [ -f "$CMAKE_PATH_AWH/FindAWH.cmake" ] && [ -d "$CMAKE_PATH/Modules" ]; then
	# Выводим сообщение, что мы запустили процесс регистрации
	echo "Process registration CMake started"
	# Перемещаем CMake файл в нужный нам каталог
	ln -s $CMAKE_PATH_AWH/FindAWH.cmake "$CMAKE_PATH/Modules"/FindAWH.cmake
	# Выводим сообщение, что мы завершили процесс регистрации
	echo "Process registration CMake finished"
fi

# Завершаем установку
exit 0
