/**
 * @file table.hpp
 * @date 2026-08-03
 *
 * @license{LicenseRef-AWH-1.0}
 *
 * @author Yuriy Lobarev
 *
 * @telegram{forman}
 * @phone{+7 (910) 983-95-90}
 *
 * @email forman@anyks.com
 * @site https://anyks.com
 *
 * \~russian
 * @brief Заголовочный файл таблиц соответствия однобайтовых кодировок Юникоду —
 *        объявления набора таблиц кодировок и таблицы имён, которыми кодировки
 *        обозначаются в заголовках сетевых протоколов
 *
 * \~english
 * @brief Header file of the single-byte encodings to Unicode correspondence tables —
 *        declarations of the set of encoding tables and of the table of names by which
 *        encodings are designated in the headers of network protocols
 *
 * \~
 *
 * @copyright Copyright © 2026
 *
 */

/**
 * Экранируем повторную инициализацию модуля
 */
#ifndef __AWH_CHARSET_TABLE__
#define __AWH_CHARSET_TABLE__

/**
 * Стандартные заголовочные файлы
 */
#include <cstdint>

/**
 * Подключаем заголовочные файлы модуля
 */
#include "types.hpp"

/**
 * \~russian
 * @brief Основное пространство имён
 *
 * \~english
 * @brief Main namespace
 *
 * \~
 */
namespace awh {
	/**
	 * Используем стандартное пространство имён
	 */
	using namespace std;

	/**
	 * \~russian
	 * @brief Пространство имён модуля перекодировки
	 *
	 * \~english
	 * @brief Namespace of the transcoding module
	 *
	 * \~
	 */
	namespace charset {
		/**
		 * \~russian
		 * @brief Таблицы кодировок, порождаемые средством «tools/encoding/charset/generate.py»
		 *
		 * \~english
		 * @brief Encoding tables generated by the "tools/encoding/charset/generate.py" tool
		 *
		 * \~
		 */
		extern __AWH_SHARED_EXPORT__ const table_t CODEPAGES[];
		extern __AWH_SHARED_EXPORT__ const size_t CODEPAGES_COUNT;
		extern __AWH_SHARED_EXPORT__ const labeling_t LABELS[];
		extern __AWH_SHARED_EXPORT__ const size_t LABELS_COUNT;
	};
};

#endif // __AWH_CHARSET_TABLE__
