/**
 * @file table.hpp
 * @date 2026-08-03
 *
 * @license{LicenseRef-AWH-1.0}
 *
 * @author Yuriy Lobarev
 *
 * @telegram{forman}
 * @phone{+7 (910) 983-95-90}
 *
 * @email forman@anyks.com
 * @site https://anyks.com
 *
 * \~russian
 * @brief Заголовочный файл таблиц приведения доменных имён — объявления таблицы
 *        преобразований символов, набора кодовых значений преобразований
 *        и таблицы видов соединения символов
 *
 * \~english
 * @brief Header file of the domain name mapping tables — declarations of the character
 *        transformations table, of the set of transformation code values and of the table
 *        of character joining types
 *
 * \~
 *
 * @copyright Copyright © 2026
 *
 */

/**
 * Экранируем повторную инициализацию модуля
 */
#ifndef __AWH_IDNA_TABLE__
#define __AWH_IDNA_TABLE__

/**
 * Стандартные заголовочные файлы
 */
#include <cstdint>

/**
 * Подключаем заголовочные файлы модуля
 */
#include "types.hpp"

/**
 * \~russian
 * @brief Основное пространство имён
 *
 * \~english
 * @brief Main namespace
 *
 * \~
 */
namespace awh {
	/**
	 * Используем стандартное пространство имён
	 */
	using namespace std;

	/**
	 * \~russian
	 * @brief Пространство имён модуля приведения доменных имён
	 *
	 * \~english
	 * @brief Namespace of the domain name mapping module
	 *
	 * \~
	 */
	namespace idna {
		/**
		 * \~russian
		 * @brief Таблицы приведения доменных имён, порождаемые средством «tools/encoding/idna/generate.py»
		 *
		 * \~english
		 * @brief Domain name mapping tables generated by the "tools/encoding/idna/generate.py" tool
		 *
		 * \~
		 */
		extern __AWH_SHARED_EXPORT__ const mapping_t MAPPINGS[];
		extern __AWH_SHARED_EXPORT__ const size_t MAPPINGS_COUNT;
		extern __AWH_SHARED_EXPORT__ const uint32_t MAPPING_SETS[];
		extern __AWH_SHARED_EXPORT__ const joining_range_t JOININGS[];
		extern __AWH_SHARED_EXPORT__ const size_t JOININGS_COUNT;
	};
};

#endif // __AWH_IDNA_TABLE__
