#!/bin/sh

modprobe sctp
sysctl -w net.sctp.auth_enable=1

# Получаем каталог с модулями CMake
readonly CMAKE_PATH=$(cmake --system-information | grep CMAKE_ROOT | cut -d= -f2 | awk '{print $2}' | sed "s/^\([\"']\)\(.*\)\1\$/\2/g")

# Если ссылка уже существует
if [ -f "$CMAKE_PATH/Modules/FindAWH.cmake" ]; then
	# Удаляем устаревшую ссылку
	rm "$CMAKE_PATH/Modules"/FindAWH.cmake
fi

# Выполняем перемещение файла CMake
ln -s /usr/share/awh/cmake/FindAWH.cmake "$CMAKE_PATH/Modules"/FindAWH.cmake

# Завершаем установку
exit 0
