cmake_minimum_required(VERSION 3.10)
project(tunnel-macos CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_library(COREFOUNDATION CoreFoundation)
add_executable(tunnel-server server.cpp tunnel.cpp)
add_executable(tunnel-client client.cpp tunnel.cpp)
target_link_libraries(tunnel-server ${COREFOUNDATION})
target_link_libraries(tunnel-client ${COREFOUNDATION})
